ZenML Month of MLOps Recap Blog Post
zenml-io/blog.zenml.io pull request #134
Opened 2022-11-21 22:16 UTC by htahir1

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
Briefly describe the changes you have introduced.

2022-11-22 07:00 UTC, dnth requested changes
I added some cosmetic changes. Otherwise looks good to me :)

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +The inaugural ZenML [Month of MLOps](https://zenml.io/competition) ran from rom October 10 to November 11, 2022. ending recently with a [closing ceremony streamed live](https://www.youtube.com/watch?
```suggestion
The inaugural ZenML [Month of MLOps](https://zenml.io/competition) ran from October 10 to November 11, 2022. ending recently with a [closing ceremony streamed live](https://www.youtube.com/watch?v=acLrHtjiN9A). The goal of the competition was to make the most creative and innovative showcase of a production-grade ZenML MLOps pipeline. Aside from the cash prizes, joining the competition was a great way to contribute to open-source software, build a machine learning portfolio, and learn MLOps best practices.
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +We were more than excited to welcome some of most well-renowned experts of the MLOps world to judge over proceedings:
```suggestion
We were more than excited to welcome some of the most well-renowned experts of the MLOps world to judge over proceedings:
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +The winners of the competition was an absolutely stellar submission by the [Fuzzy Labs](https://fuzzylabs.ai)
```suggestion
The winner of the competition was an absolutely stellar submission by the [Fuzzy Labs](https://fuzzylabs.ai)
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +Team Two were fittingly in second position, with a very neatly implemented financial payment fraud detection pipeline. They based their work on a real-world use-case that they are currently working o
```suggestion
Team Two was fittingly in the second position, with a very neatly implemented financial payment fraud detection pipeline. They based their work on a real-world use-case that they are currently working on in their actual jobs at [two](https://two.inc/), so the submission was one of the most realistic takes on a working MLOps system. Well deserved and kudos to the team!
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +Summary (in their own words): ChequeEasy is a project that aims to simply the process of approval of cheques. Leveraging AI to extract relevant data from cheques and make the whole process quicker an
```suggestion
Summary (in their own words): ChequeEasy is a project that aims to simplify the process of approval of cheques. Leveraging AI to extract relevant data from cheques and make the whole process quicker and easier for both bank officials and bank customers.
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +Shivalika's submission was particularly impressive as it was her first experience of MLOps, and she absolutely nailed it! The demo works smoothly, and shows off how easy it is to export ZenML models
```suggestion
Shivalika's submission was particularly impressive as it was her first experience with MLOps, and she absolutely nailed it! The demo works smoothly and shows off how easy it is to export ZenML models to the [HuggingFace Hub](https://huggingface.co/docs/hub/models-the-hub). Great job, Shivalika!
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +Marina's tongue-in-cheek personality carried over well with this fun project, which showcased a simple object detection pipeline, with data validation, re-training, and deployment baked in. She detai
```suggestion
Marina's tongue-in-cheek personality carried over well with this fun project, which showcased a simple object detection pipeline, with data validation, re-training, and deployment baked in. She detailed her journey in a [blog post](https://marinawyss.github.io/are-you-a-cat/), which was well received by the judges and bagged the most promising entry!
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +Andrew and Aleks were one of our youngest participants in the competition, with Andrew only recently having graduated from high school - wow what a start to their MLOps career! After implementing a g
```suggestion
Andrew and Aleks were one of our youngest participants in the competition, with Andrew only recently having graduated from high school - wow what a start to their MLOps career! After implementing a good chunk of their project in the fantastic [Full Stack Deep Learning](https://fullstackdeeplearning.com/) course, under the tutelage of Charles Frye, team Admirer continued their work with this submission. The overall result was a great continuation of their work and a worthy winner of most promising entry!
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +- The biggest factor of not being able to submit a project was **transitioning to the cloud**.
```suggestion
- The biggest factor in not being able to submit a project was **transitioning to the cloud**.
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +If you missed out on the prizes this time, or would like to participate in competitions like the Month of MLOps, join the [ZenML Slack Community](https://zenml.io/slack-invite), and keep an eye out f
```suggestion
If you missed out on the prizes this time, or would like to participate in competitions like the Month of MLOps, join the [ZenML Slack Community](https://zenml.io/slack-invite), and keep an eye out for more exciting announcements coming soon!

![image](../assets/posts/competition-recap/Final.png)
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +
```suggestion
<div class="embed-responsive embed-responsive-16by9 mb-5">
    <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/EE2Z2l_hxVA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +
I included short clips of the winners presenting during the closing ceremony

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +GitHub repo: https://github.com/two-inc/zenml-competition
```suggestion
### 🏅 2nd Prize - Two (Detecting Fraudulent Financial Transactions with ZenML)

<div class="embed-responsive embed-responsive-16by9 mb-5">
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/E9FsXqHaSwM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

GitHub repo: https://github.com/two-inc/zenml-competition
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +Demo: https://huggingface.co/spaces/shivi/ChequeEasy
```suggestion
### 🏅 3rd Prize - Shivalika Singh (ChequeEasy: Banking with Transformers)

<div class="embed-responsive embed-responsive-16by9 mb-5">
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/b0_xSISvcfU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

GitHub repo: https://github.com/shivalikasingh95/cheque-easy
Demo: https://huggingface.co/spaces/shivi/ChequeEasy
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +GitHub repo: https://github.com/MarinaWyss/are-you-a-cat
```suggestion
### 🏅 Most Promising Entry - Marina Wyss (Are You A Cat?)

<div class="embed-responsive embed-responsive-16by9 mb-5">
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/2Uqm0KgOC_A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

GitHub repo: https://github.com/MarinaWyss/are-you-a-cat
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +GitHub repo: https://github.com/andrewhinh/admirer
```suggestion
### 🏅 Most Promising Entry - Andrew Hinh and Aleks Hiidenhovi (Admirer)

<div class="embed-responsive embed-responsive-16by9 mb-5">
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/WYb3xBIOYvg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

GitHub repo: https://github.com/andrewhinh/admirer
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +  path: /assets/posts/competition-recap/Final.png
I made a thumbnail GIF for this. Let's put this in?

![Month of mlops 2022](https://user-images.githubusercontent.com/6821286/203242204-ca9a7392-2aba-4533-9e14-9479787b916d.gif)

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +## 🎖️Announcing our winners!
```suggestion
## 🎖️ Announcing our winners!
```

2022-11-22 07:00 UTC, dnth commented on _posts/2022-11-22-mlops-competition-recap.md
> +### 🎖️ 1st Prize - Fuzzy Labs (Dobble on the Edge)
```suggestion
### 🏅 1st Prize - Fuzzy Labs (Dobble on the Edge)
```

2022-11-25 11:24 UTC, dnth commented
@htahir1 we are posting this first thing on Monday, can we merge this already?

2022-11-25 11:28 UTC, htahir1 commented
@dnth I guess we can do it already

2022-11-25 12:03 UTC, merged