First draft of blog for Admirer
zenml-io/blog.zenml.io pull request #147
Opened 2022-12-20 19:14 UTC by andrewhinh

## Pre-requisites
Please ensure you have done the following:
- [x] I have read the **CONTRIBUTING.md** document.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe changes
Briefly describe the changes you have introduced.

2022-12-21 10:58 UTC, strickvl requested changes
A couple of small changes that I can see, but otherwise looks good to me!

2022-12-21 10:58 UTC, strickvl commented on _posts/2022-12-19-month-of-mlops-most-promising-entry-prize-admirer.md
> +author: "The Transformees: Andrew Hinh and Aleks Hiidenhovi(Guest post)"
```suggestion
author: "The Transformees: Andrew Hinh and Aleks Hiidenhovi (Guest post)"
```

2022-12-21 10:58 UTC, strickvl commented on _posts/2022-12-19-month-of-mlops-most-promising-entry-prize-admirer.md
> +The second is creating data, training, and testing pipelines with both Makefiles and ZenML pipelines. This allows us to more easily iterate through ideas to improve the pipeline's performance and add
```suggestion
The second is creating data, training, and testing pipelines with both Makefiles and ZenML pipelines. This allows us to more easily iterate through ideas to improve the pipeline's performance and add features such as continual training, a feature of MLOps projects that ZenML goes into detail [here](https://blog.zenml.io/ci-ct-cd-with-zenml/). In addition, it allows others to more easily reproduce and test our work.
```

2022-12-21 10:58 UTC, strickvl commented on _posts/2022-12-19-month-of-mlops-most-promising-entry-prize-admirer.md
> +Having recently built a MVP of the project for the Full Stack Deep Learning course, we were excited to build out the data management and training pipelines for this competition. We were not disappoin
```suggestion
Having recently built a MVP of the project for the [Full Stack Deep Learning course](https://fullstackdeeplearning.com/), we were excited to build out the data management and training pipelines for this competition. We were not disappointed: we got a chance to get our hands dirty building out the pipelines, showcase our work to numerous experts in the field and receive their feedback, and win the "Most Promising Entry" award! We'd like to thank the ZenML team for organizing this competition and the judges for their invaluable feedback.
```

2022-12-21 11:29 UTC, htahir1 commented
@andrewhinh Thanks for the review! We'll try to ge tthis out tomorrow if you can accept the reviewsuggestions by @strickvl

2022-12-21 15:38 UTC, andrewhinh commented
Accepted the review suggestions, thanks for the feedback!

2022-12-21 15:42 UTC, strickvl approved these changes

2022-12-23 09:36 UTC, merged

2022-12-23 10:39 UTC, htahir1 commented
@andrewhinh We are now live! We will be promoting now through the day. Please feel free to repost on social media!